# Generated by Django 4.2.4 on 2023-08-07 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='isim')),
                ('surname', models.CharField(max_length=100, null=True, verbose_name='Soyisim')),
                ('bio', models.TextField(default='Merhaba', max_length=500, null=True, verbose_name='Hakkinda')),
                ('image', models.FileField(null=True, upload_to='profiles/', verbose_name='Profil Resmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Olusturulma Tarihi')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
