# Generated by Django 5.0.6 on 2024-07-14 20:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Birlestirme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FramePhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fimage", models.ImageField(upload_to="photos/")),
                (
                    "flatitude",
                    models.FloatField(blank=True, max_length=200000, null=True),
                ),
                (
                    "flongitude",
                    models.FloatField(blank=True, max_length=200000, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Images",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="resimler/"),
                ),
                ("gps_latitude", models.FloatField(blank=True, null=True)),
                ("gps_longitude", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isim", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Arazi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("isim", models.CharField(max_length=100, null=True)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="araziler/"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="olusturulma tarihi"
                    ),
                ),
                (
                    "arsasahibi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="user.profile"
                    ),
                ),
                (
                    "kategori",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="agaclar.kategori",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agac",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "aimage",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("alatitude", models.FloatField(blank=True, null=True)),
                ("alongitude", models.FloatField(blank=True, null=True)),
                (
                    "qr_code",
                    models.ImageField(blank=True, null=True, upload_to="qrcodes/"),
                ),
                ("ozellik", models.TextField(default="Ozellik", max_length=500)),
                (
                    "arazi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="agaclar.arazi"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Konum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(blank=True, max_length=200000, null=True)),
                ("long", models.FloatField(blank=True, max_length=20000, null=True)),
                ("address", models.TextField(default="Bilinmeyen Adres")),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField(default="Content", max_length=2000)),
                (
                    "arazi",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agaclar.arazi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LatLong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.FloatField(blank=True, null=True)),
                ("long", models.FloatField(blank=True, null=True)),
                (
                    "birlestirme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lat_long_values",
                        to="agaclar.birlestirme",
                    ),
                ),
            ],
        ),
    ]
